**Taller Semana 1:**


Durante los talleres trabajaremos con los contenidos del curso, de manera paralela a la teoría, pero utilizaremos la herramienta (lenguaje de programación) Python para resolver los distintos problemas.
En esta semana implementaremos las funciones de Python asociadas a los contenidos previos del curso.

A continuación encontrarán una serie de calculos que deben ser realizados a través de Python, debajo de cada item deben escribir el código que resuelve el problema y en caso de ser necesario, comentar su resultado agregando un cuadro de texto.

Considere la siguiente tabla de frecuencias que representa los Sueldos de un grupo de empleados en miles de pesos:

$$\begin{array}{|c|c|}\hline
\text{Sueldo}&\text{Empleados}\\ \hline
300-400&25\\ \hline
400-500&43\\ \hline
500-600&39\\ \hline
600-700&32\\ \hline
700-800&14\\ \hline
800-900&12\\ \hline
900-1000&8\\ \hline
\end{array}$$



1. Ingrese las librerias necesarias para utilizar los códigos de Python.

In [ ]:
import numpy as np

2. Ingrese los datos a Python, esto es necesario para poder realizar los calculos siguientes.

In [ ]:

sueldo_minimo = [300, 400, 500, 600, 700, 800, 900]
sueldo_maximo = [400, 500, 600, 700, 800, 900, 1000]
emp = [25, 43, 39, 32, 14, 12, 8]

datos = np.array(list(zip(sueldo_minimo, sueldo_maximo, emp)))
print(datos)

[[ 300  400   25]
 [ 400  500   43]
 [ 500  600   39]
 [ 600  700   32]
 [ 700  800   14]
 [ 800  900   12]
 [ 900 1000    8]]


3. Determine el número de empleados que tiene la empresa.




In [ ]:
print(np.sum(emp))

173


4. Encuentre la media aritmética o promedio de los sueldos.



In [ ]:
total = np.sum(emp)
proms = np.mean(sueldo_minimo, sueldo_maximo)
print(proms)

TypeError: ignored

5. Encuentre la varianza de los sueldos.


6. Encuentre la desviación estándar de los sueldos.

7. Encuentre el coeficiente de variación y comente su significado.